services:
  # Self-hosted mode (recommended for development or fun)
  docklord-self-hosted:
    container_name: docklord-self-hosted
    image: docklord-self-hosted
    build: .
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
      - "${GRPC_PORT:-50051}:${GRPC_PORT:-50051}"
    command: ["--type", "self-hosted"]
    environment:
      - RUST_LOG=info
      - API_PORT=${API_PORT:-3000}
      - GRPC_PORT=${GRPC_PORT:-50051}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Coordinator only
  docklord-coordinator:
    container_name: docklord-coordinator
    image: docklord-coordinator
    build: .
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
      - "${GRPC_PORT:-50051}:${GRPC_PORT:-50051}"
    command: ["--type", "coordinator"]
    environment:
      - RUST_LOG=info
      - API_PORT=${API_PORT:-3000}
      - GRPC_PORT=${GRPC_PORT:-50051}
    restart: unless-stopped

  # Node only (connects to coordinator)
  docklord-node:
    container_name: docklord-node
    image: docklord-node
    build: .
    command:
      [
        "--type",
        "node",
        "--coordinator-addr",
        "${COORDINATOR_ADDR:-http://82.27.2.230:50051}",
      ]
    environment:
      - RUST_LOG=info
      - COORDINATOR_ADDR=${COORDINATOR_ADDR:-http://82.27.2.230:50051}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
