[package]
name = "docklord-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
coordinator-runner = { path = "../../coordinator/services/coordinator-runner" }
node-runner = { path = "../../node/services/node-runner" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.9.1"

[lints]
workspace = true
